Resources:
  CloudfrontS3OriginAccess:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront OAI for ${self:service.name}-${opt:stage}
  CloudFrontOrigin:
    Type: AWS::CloudFront::Distribution
    DependsOn:
    - S3WebsiteBucket
    Properties:
      DistributionConfig:
        Comment: ${opt:stage}
        Origins:
        - DomainName: !GetAtt S3WebsiteBucket.DomainName
          Id: S3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CloudfrontS3OriginAccess]]
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        CustomErrorResponses:
        - ErrorCode: 404
          ResponseCode: 200
          ResponsePagePath: /index.html
          ErrorCachingMinTTL: 0
      Tags:
        - 
          Key: "Project"
          Value: "FETT-Portal"
        - 
          Key: "Environment"
          Value: ${opt:stage, 'develop'}
        - 
          Key: "CreatedBy"
          Value: "Kurt Hopfer"          
  S3WebsiteBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: ${self:service.name}-hosting-${opt:stage}
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - GET
          AllowedOrigins:
          - "*"
          MaxAge: 1800
      Tags:
        - 
          Key: "Project"
          Value: "FETT-Portal"
        - 
          Key: "Environment"
          Value: ${opt:stage, 'develop'}
        - 
          Key: "CreatedBy"
          Value: "Kurt Hopfer"          
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: S3WesitePolicy
        Version: '2012-10-17'
        Statement:
          - 
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudfrontS3OriginAccess.S3CanonicalUserId
            Action:
              - s3:GetObject
              - s3:List*
            Resource: 
              - !Join [ '', [ 'arn:aws:s3:::', !Ref S3WebsiteBucket, '/*' ] ]
              - !Join [ '', [ 'arn:aws:s3:::', !Ref S3WebsiteBucket ] ]
      Bucket:
        Ref: S3WebsiteBucket