Resources:
  ResearcherArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ${opt:stage}-ssith-fett-target-researcher-artifacts
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: 'kurt.hopfer@fivetalent.com'
        Protocol: email
  ResearcherInitializationQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true 
      VisibilityTimeout: 900
  InstanceStatusQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      VisibilityTimeout: 60
  PortalToInstanceTerminationQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
