Resources:
  ResearcherArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ${opt:stage}-ssith-fett-target-researcher-artifacts
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint: 'kurt.hopfer@fivetalent.com'
        Protocol: email
  ResearcherInitializationQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true 
      VisibilityTimeout: 900
  InstanceStatusQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      VisibilityTimeout: 60
  PortalToInstanceTerminationQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 60
      MessageRetentionPeriod: 240
  LearningBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ${opt:stage}-ssith-fett-target-learn-docs
      AccessControl: Private
  # BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     PolicyDocument:
  #       Id: S3LearnPolicy
  #       Version: '2012-10-17'
  #       Statement: 
  #       - 
  #         Action: 
  #           - "s3:GetObject"
  #         Effect: "Allow"
  #         Resource:
  #           Fn::Join: 
  #             - ""
  #             - 
  #               - "arn:aws:s3:::"
  #               - 
  #                 Ref: "LearningBucket"
  #               - "/*"
  #         Principal:
  #           Fn::Join:
  #             - ""
  #             - 
  #               - "arn:aws:iam::"
  #               - Ref: AWS::AccountId
  #               - role/${opt:stage}-fettportal-us-west-2-lambdaRole
  #     Bucket:
  #       Ref: LearningBucket