service:
  name: fettportal
plugins:
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-offline
package:
  individually: true
  exclude:
    - exclude-me.js
    - front-end/**
provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2
  stage: ${opt:stage, 'dev'}
  stackName: ${opt:stage, 'dev'}-${self:service.name}
  versionFunctions: false
  deploymentBucket: !Ref ${self:service.name-${opt:stage, 'dev'}-artifacts
  tags:
    Project: FETT-Portal
    Environment: ${opt:stage, 'dev'}
    CreatedBy: Kurt Hopfer
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: '*'
    - Effect: "Allow"
      Action:
        - "ssm:GetParametersByPath"
        - "ssm:GetParameter"
        - "ssm:PutParameter"
      Resource:
        - "arn:aws:ssm:us-west-2:#{AWS::AccountId}:parameter/fettportal/*" # RDS CREDS
        - "arn:aws:ssm:us-west-2:#{AWS::AccountId}:parameter/fettportal/*"
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - ${file(cloudformation/outputs.yml):Outputs.AlarmTopicArn.Value}
  vpc:
    securityGroupIds:
      - ${file(./config/config.${self:provider.stage}.json):VPC_SECURITY_GROUP_ID}
    subnetIds:
      - ${file(./config/config.${self:provider.stage}.json):VPC_SUBNET_ID_1}
      - ${file(./config/config.${self:provider.stage}.json):VPC_SUBNET_ID_2}
      - ${file(./config/config.${self:provider.stage}.json):VPC_SUBNET_ID_3}
  environment:
    region: ${self:provider.region}
    stage: ${self:provider.stage}
    alarmTopicArn: ${file(cloudformation/outputs.yml):Outputs.AlarmTopicArn.Value}
custom:
  webpackIncludeModules: true
  webpack:
    webpackConfig: ./webpack.config.js
    packager: 'npm'
  lambdaArnBase: "arn:aws:lambda:${self:provider.region}:#{AWS::AccountId}:function:${self:service.name}-${self:provider.stage}"
  authorizerPool:
    dev: arn:aws:cognito-idp:us-west-2:319580086754:userpool/us-west-2_thdiGaAES
  ingestionEnabled:
    dev: true
functions:
  getFromDatabase:
    handler: src/functions/getFromDatabase.handler
    timeout: 60
    events:
    - http:
        path: getFromDatabase
        method: get
        cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
        authorizer:
          name: authorizer
          arn: ${self:custom.authorizerPool.${self:provider.stage}}
    vpc: 
      securityGroupIds:
        - !Ref LambdaSecurityGroup
resources:
  - ${file(cloudformation/hosting.yml)}
  - ${file(cloudformation/resources.yml)}
  - ${file(cloudformation/outputs.yml)}
  - ${file(cloudformation/aurora.yml)}


